services:
  - type: web
    name: agrimitra-backend
    env: python
    buildCommand: "cd backend && pip install --no-cache-dir -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_MODEL
        value: nvidia/nemotron-3-nano-omni-30b-a3b-reasoning
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: WEATHERAPI_KEY
        sync: false
      - key: DATAGOV_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: agrimitra-scans
      - key: FRONTEND_URL
        value: "*"
